- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
    update_cache: yes

- name: "Define role executed var {{ role_name }}_was_executed"
  set_fact:
    "{{ role_name }}_was_executed": true
    cacheable: true