- name: Create docker compose yaml
  template:
    src: docker-compose.yml
    dest: "/srv/compose/docker-compose.yml"

- name: Create docker compose env
  template:
    src: compose.env
    dest: "/srv/compose/compose.env"

- name: Start docker compose
  docker_compose:
    project_src: "/srv/compose/"
    recreate: always
    restarted: yes