### GitLab CI use this compose

version: "3.5"
services:
  yatube:
    image: yatube:latest
    container_name: yatube
    restart: always
    env_file:
      - compose.env
    sysctls:
      net.core.somaxconn: 1024
    networks:
      - traefik
    volumes:
      - /srv/docker/app/static:/opt/app/static
      - /srv/docker/app/media:/opt/app/media
      - /srv/docker/app/database:/opt/app/database
      - /srv/docker/app/sent_emails:/opt/app/sent_emails
    labels:
      traefik.claim.frontend.rule: "Host:praktikum.must-hw.pw"
      traefik.protocol: "http"
      traefik.enable: "true"
      traefik.port: "8000"
      traefik.docker.network: traefik

networks:
  traefik:
    external: true